name: Build App
on:
  push:
    branches:
      - main
jobs:
  build:
    name: build electron app
    runs-on: ${{matrix.os}}

    # mac and windows
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3.0.0

      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16'

      - name: Install and build
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: Upload file
        uses: actions/upload-artifact@v2
        with:
          name: kafka-desktop
          path: release
